Repository openrewrite/rewrite-gradle-plugin, pull requests merged in 2024-08, with the labels that each got.

#228 Issue #227: Incompatible with the configuration cache
  plugin/src/main/java/org/openrewrite/gradle/AbstractRewriteTask.java
  plugin/src/main/java/org/openrewrite/gradle/ResolveRewriteDependenciesTask.java
  plugin/src/main/java/org/openrewrite/gradle/RewriteDryRunTask.java
  plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
  plugin/src/test/kotlin/org/openrewrite/gradle/RewriteDiscoverTest.kt
  plugin/src/test/kotlin/org/openrewrite/gradle/RewriteDryRunTest.kt
  plugin/src/test/kotlin/org/openrewrite/gradle/RewritePluginTest.kt
  plugin/src/test/kotlin/org/openrewrite/gradle/RewriteResolveDependenciesTest.kt
  plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Labels: enhancement, parser-gradle

#313 Drop interactity from `rewriteDiscover`
  plugin/src/main/java/org/openrewrite/gradle/DelegatingProjectParser.java
  plugin/src/main/java/org/openrewrite/gradle/GradleProjectParser.java
  plugin/src/main/java/org/openrewrite/gradle/RewriteDiscoverTask.java
  plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
  plugin/src/main/java/org/openrewrite/gradle/isolated/ui/RecipeDescriptorTree.java
  plugin/src/main/java/org/openrewrite/gradle/isolated/ui/RecipeDescriptorTreePrompter.java
  plugin/src/main/java/org/openrewrite/gradle/isolated/ui/package-info.java
Labels: enhancement

#295 refactor: Update Gradle wrapper
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#314 Add JavaVersion marker to files in Java project resources directories
  plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
  plugin/src/test/kotlin/org/openrewrite/gradle/RewriteRunTest.kt
Labels: enhancement

#316 Look for ParseExceptionResult marker instead of instanceof ParserError
  plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Labels: enhancement

#322 Do not add Kotlin and Groovy sources from `build/` to LST
  plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Labels: bug

#325 Don't init the gradle parser until we have confirmed the settings files is not excluded.
  plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java
Labels: enhancement

#326 Update RewritePlugin to load tasks lazily
  plugin/src/main/java/org/openrewrite/gradle/RewritePlugin.java
Labels: enhancement
